learning_users/basic_app/urls.py
from django.conf.urls import url
from . import views

# Template URLs
app_name = 'basic_app'

urlpatterns = [
    url(r'^register/', views.register, name='register'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from basic_app import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^basic_app/', include('basic_app.urls')),
    url(r'^logout/$', views.user_logout, name = 'logout'),
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    #Create relationship without enheritance
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #Add any aditional attributes
    portfolio = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio', 'picture')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserForm, UserProfileInfoForm

#
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()

            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request, 'basic_app/registration.html', {'user_form':user_form, 'profile_form':profile_form, 'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Account not active")
        else:
            print("Someone tried to login and failed")
            print("Username {} and password {}".format(username, password))
            return HttpResponse("Invalid login details supplied")
    else:
        return render(request, "basic_app/login.html", {})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
  </head>
  <body>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet"/>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li><a class="navbar-brand" href="{% url 'index' %}">Django</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Register</a></li>
          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Log out</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Log in</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      <!-- Anything outside of this will be inherited if you extend! -->
      {% endblock %}
    </div>

  </body>
</html>

learning_users/templates/basic_app/index.html
{% extends "basic_app/base.html" %}
  {% block body_block %}
    <div class="jumbotron">
        <h1>Django Level Five</h1>
    </div>
  {% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Log in</h1>
    <form action="{% url 'basic_app:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="Enter username">

      <label for="password">Password:</label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">

    </form>
  </div>
{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html' %}
{% load staticfiles %}

{% block body_block %}
<div class="">
  {% if registered %}
    <h1>Thank you for registering</h1>
  {% else %}
    <h1>Register here</h1>
    <h3>Fill out the form:</h3>
    <form enctype="multipart/form-data"  method="post">
      {% csrf_token %}
      {{ user_form.as_p }}
      {{ profile_form.as_p }}
      <input type="submit" name="" value="Register">
    </form>
  {% endif %}
</div>
{% endblock %}